server:
  port: 9093

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hrcommentdb
      username: Java8User
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgejava8
    password: bilgeadmin*