server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hrcompanydb
      username: companyadmin
      password: 12345
  rabbitmq:
    host: localhost
    port: 5672
    username: java8
    password: root