server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hrcompanydb
      username: mongoadmin
      password: secret
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: secret