server:
  port: 9092

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hruserdb
      username: Java8User
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: java8
    password: root
