server:
  port: 9095

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hruserdb
      username: hrmanagementadmin
      password: hrmanagement33**
  rabbitmq:
    host: localhost
    port: 5672
    username: java8
    password: root
