server:
  port: 8889

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/muhammetkrkrt/ConfigHr.git
          default-label: master
          skip-ssl-validation: true
          username: muhammetkrkrt
          password: ${GIT_CONFIG_PASS}
