server:
  port: 9091

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hrcompanydb
      username: ${MONGO_USERNAME_COMPANY}
      password: ${MONGO_PASS_COMPANY}
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASS}