server:
  port: 9095

  tomcat:
    max-http-header-size: 819200

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: hruserdb
      username: ${MONGO_USERNAME_USER}
      password: ${MONGO_PASS_USER}
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASS}
